
import { User } from './types';

export const USERS: User[] = [
  {
    id: 1,
    name: 'Felício Facilitie',
    units: ['Mooca', 'Brás', 'Tatuapé'],
    unidade: 'Mooca',
    entidade: 'SENAI',
    razaoSocial: 'ALFER PRESTADORA DE SERVICOS LTDA',
    cnpj: '01.456.620/0001-00',
    cpf: '123.456.789-10',
    escolaridade: 'Ensino Superior Completo',
    genero: 'Masculino',
    logradouro: 'Rua da Mooca, 1234, São Paulo - SP',
    dataNascimento: '10/05/1985',
    cargo: 'Gerente de Facilidades',
    dataInicioVinculo: '15/03/2020',
    dataInicioAtividades: '20/03/2020',
    jornadaTrabalho: '40 horas semanais',
    recebeAdicional: false,
  },
  {
    id: 2,
    name: 'Gabriela Galera',
    units: ['Osasco', 'Carapicuiba'],
    unidade: 'Osasco',
    entidade: 'SESI',
    razaoSocial: 'SECURITY SEGURANCA LTDA',
    cnpj: '02.789.123/0001-05',
    cpf: '987.654.321-20',
    escolaridade: 'Ensino Médio Completo',
    genero: 'Feminino',
    logradouro: 'Avenida dos Autonomistas, 500, Osasco - SP',
    dataNascimento: '22/08/1992',
    cargo: 'Vigilante',
    dataInicioVinculo: '01/02/2021',
    dataInicioAtividades: '05/02/2021',
    jornadaTrabalho: '12x36',
    recebeAdicional: true,
  },
  {
    id: 3,
    name: 'Milton Melo',
    units: ['Mauá', 'Ribeirão Pires'],
    unidade: 'Mauá',
    entidade: 'SENAI',
    razaoSocial: 'JARDINAGEM E PAISAGISMO SILVA',
    cnpj: '03.159.753/0001-08',
    cpf: '159.753.486-30',
    escolaridade: 'Ensino Fundamental Completo',
    genero: 'Masculino',
    logradouro: 'Rua das Orquídeas, 78, Mauá - SP',
    dataNascimento: '30/11/1980',
    cargo: 'Jardineiro',
    dataInicioVinculo: '10/10/2018',
    dataInicioAtividades: '15/10/2018',
    jornadaTrabalho: '44 horas semanais',
    recebeAdicional: false,
  },
  {
    id: 4,
    name: 'Ana Pereira',
    units: ['Santos', 'Guarujá'],
    unidade: 'Santos',
    entidade: 'SESI',
    razaoSocial: 'LIMPEZA PRAIANA LTDA',
    cnpj: '04.258.369/0001-01',
    cpf: '258.369.147-40',
    escolaridade: 'Ensino Médio Completo',
    genero: 'Feminino',
    logradouro: 'Avenida da Praia, 999, Santos - SP',
    dataNascimento: '05/01/1995',
    cargo: 'Auxiliar de Limpeza',
    dataInicioVinculo: '01/06/2022',
    dataInicioAtividades: '02/06/2022',
    jornadaTrabalho: '40 horas semanais',
    recebeAdicional: true,
  },
  {
    id: 5,
    name: 'Carlos Souza',
    units: ['Campinas', 'Valinhos'],
    unidade: 'Campinas',
    entidade: 'SENAI',
    razaoSocial: 'MANUTENCAO INDUSTRIAL SOUZA',
    cnpj: '05.951.753/0001-09',
    cpf: '951.753.852-50',
    escolaridade: 'Curso Técnico em Mecânica',
    genero: 'Masculino',
    logradouro: 'Rua Industrial, 300, Campinas - SP',
    dataNascimento: '18/07/1988',
    cargo: 'Técnico de Manutenção',
    dataInicioVinculo: '20/09/2019',
    dataInicioAtividades: '25/09/2019',
    jornadaTrabalho: '44 horas semanais',
    recebeAdicional: true,
  },
];
